import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import {
  STATUS,
  ERROR_RESPONSE,
  getMoviesByCategoryURL,
} from "utils/constants";
import _fetch from "utils/_fetch";

const initialState = { status: STATUS.IDLE, error: null, data: {} };

export const fetchMoviesByCategory = createAsyncThunk(
  "moviesByCategory/fetchMoviesByCategory",
  async (category, { rejectWithValue }) => {
    try {
      // const response = await fetch(getMoviesByCategoryURL(category));
      const response = await _fetch(category);
      const data = await response.json();

      if (!data?.results || data?.status_message) {
        throw new Error(data?.status_message || ERROR_RESPONSE);
      }

      return data;
    } catch (error) {
      return rejectWithValue(error);
    }
  }
);

export const moviesByCategorySlice = createSlice({
  name: "moviesByCategory",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  /**
   * The `extraReducers` field lets the slice handle actions defined elsewhere,
   *  including actions generated by createAsyncThunk or in other slices.
   */
  extraReducers: (builder) => {
    builder
      .addCase(fetchMoviesByCategory.pending, (state) => {
        state.status = STATUS.PENDING;
        state.error = null;
      })
      .addCase(fetchMoviesByCategory.fulfilled, (state, action) => {
        state.status = STATUS.FULFILLED;
        state.data = action.payload;
        state.error = null;
      })
      .addCase(fetchMoviesByCategory.rejected, (state, action) => {
        state.status = STATUS.REJECTED;
        state.data = {};
        state.error = action.payload;
      });
  },
});

export const selectMoviesByCategory = (state) => state.moviesByCategory;

export default moviesByCategorySlice.reducer;
